-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    address_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    city character varying(30) COLLATE pg_catalog."default",
    area character varying(150) COLLATE pg_catalog."default",
    postcode character varying(20) COLLATE pg_catalog."default",
    place_id character varying(100) COLLATE pg_catalog."default",
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point,4326),
    display_name character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT address_pkey PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS public.agencies
(
    agency_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    address_id character varying(20) COLLATE pg_catalog."default",
    owner_id character varying(20) COLLATE pg_catalog."default",
    agency_name character varying(50) COLLATE pg_catalog."default",
    phone_number character varying(11) COLLATE pg_catalog."default",
    email character varying(70) COLLATE pg_catalog."default",
    cars smallint,
    license character varying(30) COLLATE pg_catalog."default",
    tin character varying(15) COLLATE pg_catalog."default",
    insurancenumber character varying(20) COLLATE pg_catalog."default",
    tradelicenseexpire date,
    status agency_status,
    expire_date date,
    created_at date,
    verified boolean,
    bikes smallint,
    rating numeric(3, 2) DEFAULT 0,
    rating_count integer DEFAULT 0,
    review_count integer DEFAULT 0,
    CONSTRAINT agencies_pkey PRIMARY KEY (agency_id)
);

CREATE TABLE IF NOT EXISTS public.agency_reviews
(
    agency_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    date date,
    review text COLLATE pg_catalog."default",
    rating numeric(2, 1)
);

CREATE TABLE IF NOT EXISTS public.bikes
(
    bike_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    agency_id character varying(20) COLLATE pg_catalog."default",
    brand character varying(20) COLLATE pg_catalog."default",
    model character varying(20) COLLATE pg_catalog."default",
    car_type character varying(20) COLLATE pg_catalog."default",
    build_year integer,
    images text[] COLLATE pg_catalog."default",
    fuel character varying(20) COLLATE pg_catalog."default",
    fuel_capacity integer,
    mileage numeric(5, 2),
    gear smallint,
    rental_price integer,
    about text COLLATE pg_catalog."default",
    engine_capacity integer,
    helmet_count integer,
    abs boolean,
    disk_brake boolean,
    status car_status,
    engine_start_type character varying(10) COLLATE pg_catalog."default",
    verified boolean,
    next_available_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    rating numeric(3, 2) DEFAULT 0,
    rating_count integer DEFAULT 0,
    review_count integer DEFAULT 0,
    CONSTRAINT motorcycles_pkey PRIMARY KEY (bike_id)
);

CREATE TABLE IF NOT EXISTS public.booking_info
(
    booking_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    vehicle_type vehicle_type,
    vehicle_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    start_ts timestamp with time zone,
    end_ts timestamp with time zone,
    booking_ts timestamp with time zone,
    total_rent_hours smallint,
    driver_cost smallint,
    total_cost integer,
    initial_payment boolean,
    final_payment boolean,
    status booking_status,
    driver_id character varying(20) COLLATE pg_catalog."default",
    period tstzrange GENERATED ALWAYS AS (tstzrange(start_ts, end_ts, '[]'::text)) STORED,
    user_id character varying(20) COLLATE pg_catalog."default",
    booking_purpose text COLLATE pg_catalog."default" NOT NULL,
    estimated_destination text COLLATE pg_catalog."default" NOT NULL,
    cancelled_by text COLLATE pg_catalog."default",
    cancel_reason text COLLATE pg_catalog."default",
    cancelled_at timestamp with time zone,
    CONSTRAINT booking_info_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.cars
(
    car_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    agency_id character varying(20) COLLATE pg_catalog."default",
    brand character varying(20) COLLATE pg_catalog."default",
    model character varying(20) COLLATE pg_catalog."default",
    car_type character varying(20) COLLATE pg_catalog."default",
    build_year integer,
    images text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    seats smallint,
    fuel character varying(10) COLLATE pg_catalog."default",
    mileage numeric(5, 2),
    gear smallint,
    rental_price integer,
    transmission_type character varying(20) COLLATE pg_catalog."default",
    about text COLLATE pg_catalog."default",
    air_conditioning boolean,
    gps boolean,
    bluetooth boolean,
    central_locking boolean,
    status car_status,
    verified boolean,
    next_available_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    rating numeric(3, 2) DEFAULT 0,
    rating_count integer DEFAULT 0,
    review_count integer DEFAULT 0,
    CONSTRAINT cars_pkey PRIMARY KEY (car_id)
);

CREATE TABLE IF NOT EXISTS public.cars_documentation
(
    documentation_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    car_id character varying(20) COLLATE pg_catalog."default",
    license_number character varying(30) COLLATE pg_catalog."default",
    expire_date date,
    fitness_certificate character varying(30) COLLATE pg_catalog."default",
    issuing_authority character varying(50) COLLATE pg_catalog."default",
    insurance_number character varying(30) COLLATE pg_catalog."default",
    insurance_start_date date,
    insurance_ending_date date,
    insurance_provider character varying(100) COLLATE pg_catalog."default",
    insurance_coverage_type character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT cars_documentation_pkey PRIMARY KEY (documentation_id)
);

CREATE TABLE IF NOT EXISTS public.cars_reviews
(
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    car_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    date date,
    review text COLLATE pg_catalog."default",
    rating numeric(2, 1)
);

CREATE TABLE IF NOT EXISTS public.damage_reports
(
    damage_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    booking_id character varying(20) COLLATE pg_catalog."default",
    car_id character varying(20) COLLATE pg_catalog."default",
    reported_by character varying(20) COLLATE pg_catalog."default",
    report_date date,
    damage_type character varying(100) COLLATE pg_catalog."default",
    severity damage_severity,
    description text COLLATE pg_catalog."default",
    photos text COLLATE pg_catalog."default",
    estimated_cost integer,
    status damage_status,
    CONSTRAINT damage_reports_pkey PRIMARY KEY (damage_id)
);

CREATE TABLE IF NOT EXISTS public.driver_info
(
    driver_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    agency_id character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    address_id character varying(20) COLLATE pg_catalog."default",
    name character varying(30) COLLATE pg_catalog."default",
    email character varying(70) COLLATE pg_catalog."default",
    phone character varying(10) COLLATE pg_catalog."default",
    gender character varying(16) COLLATE pg_catalog."default",
    nid character varying(16) COLLATE pg_catalog."default",
    dob date,
    photo character varying(250) COLLATE pg_catalog."default",
    verified boolean,
    accountstatus account_status,
    license_number character varying(20) COLLATE pg_catalog."default",
    license_status license_status,
    expire_date date,
    experience_year integer,
    rating numeric(3, 2) DEFAULT 0,
    rating_count integer DEFAULT 0,
    review_count integer DEFAULT 0,
    rental_price integer,
    availability boolean,
    CONSTRAINT driver_info_pkey PRIMARY KEY (driver_id)
);

CREATE TABLE IF NOT EXISTS public.driver_reviews
(
    driver_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    date date,
    review text COLLATE pg_catalog."default",
    rating numeric(2, 1)
);

CREATE TABLE IF NOT EXISTS public.motorbike_documentation
(
    documentation_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bike_id character varying(20) COLLATE pg_catalog."default",
    license_number character varying(30) COLLATE pg_catalog."default",
    expire_date date,
    fitness_certificate character varying(30) COLLATE pg_catalog."default",
    issuing_authority character varying(50) COLLATE pg_catalog."default",
    insurance_number character varying(30) COLLATE pg_catalog."default",
    insurance_start_date date,
    insurance_ending_date date,
    insurance_provider character varying(100) COLLATE pg_catalog."default",
    insurance_coverage_type character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT motorbike_documentation_pkey PRIMARY KEY (documentation_id)
);

CREATE TABLE IF NOT EXISTS public.motorbike_reviews
(
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bike_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    date date,
    review text COLLATE pg_catalog."default",
    rating numeric(2, 1)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notif_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(20) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    created_at date,
    is_read boolean,
    CONSTRAINT notifications_pkey PRIMARY KEY (notif_id)
);

CREATE TABLE IF NOT EXISTS public.payment_info
(
    payment_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    booking_id character varying(20) COLLATE pg_catalog."default",
    date timestamp without time zone,
    amount integer,
    method_type payment_method,
    trx_id character varying(50) COLLATE pg_catalog."default",
    payment_for character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT payment_info_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.pickup_info
(
    pickup_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    booking_id character varying(20) COLLATE pg_catalog."default",
    pickup_time timestamp without time zone,
    fuel_level numeric(5, 2),
    odometer_reading integer,
    early_fee integer,
    fuel_charge integer,
    pickup_notes text COLLATE pg_catalog."default",
    CONSTRAINT pickup_info_pkey PRIMARY KEY (pickup_id)
);

CREATE TABLE IF NOT EXISTS public.return_info
(
    return_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    booking_id character varying(20) COLLATE pg_catalog."default",
    return_time timestamp without time zone,
    late_hours timestamp without time zone,
    fuel_level numeric(5, 2),
    odometer_reading integer,
    late_fee integer,
    fuel_charge integer,
    cleaning_charge integer,
    return_notes text COLLATE pg_catalog."default",
    CONSTRAINT return_info_pkey PRIMARY KEY (return_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    address_id character varying(20) COLLATE pg_catalog."default",
    name character varying(30) COLLATE pg_catalog."default",
    email character varying(70) COLLATE pg_catalog."default",
    phone character varying(11) COLLATE pg_catalog."default",
    gender character varying(16) COLLATE pg_catalog."default",
    dob date,
    photo character varying(250) COLLATE pg_catalog."default",
    verified boolean,
    accountstatus account_status,
    userrole user_role,
    license_number character varying(20) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    license_status license_status,
    expire_date date,
    experience integer,
    created_at date,
    nid character varying(16) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.agencies
    ADD CONSTRAINT agencies_address_id_fkey FOREIGN KEY (address_id)
    REFERENCES public.address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.agencies
    ADD CONSTRAINT agencies_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.agency_reviews
    ADD CONSTRAINT agency_reviews_agency_id_fkey FOREIGN KEY (agency_id)
    REFERENCES public.agencies (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.agency_reviews
    ADD CONSTRAINT agency_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bikes
    ADD CONSTRAINT motorcycles_agency_id_fkey FOREIGN KEY (agency_id)
    REFERENCES public.agencies (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking_info
    ADD CONSTRAINT booking_info_driver_id_fkey FOREIGN KEY (driver_id)
    REFERENCES public.driver_info (driver_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking_info
    ADD CONSTRAINT booking_info_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cars
    ADD CONSTRAINT cars_agency_id_fkey FOREIGN KEY (agency_id)
    REFERENCES public.agencies (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cars_documentation
    ADD CONSTRAINT cars_documentation_car_id_fkey FOREIGN KEY (car_id)
    REFERENCES public.cars (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cars_reviews
    ADD CONSTRAINT cars_reviews_car_id_fkey FOREIGN KEY (car_id)
    REFERENCES public.cars (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cars_reviews
    ADD CONSTRAINT cars_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.damage_reports
    ADD CONSTRAINT damage_reports_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.booking_info (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.damage_reports
    ADD CONSTRAINT damage_reports_car_id_fkey FOREIGN KEY (car_id)
    REFERENCES public.cars (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.damage_reports
    ADD CONSTRAINT damage_reports_reported_by_fkey FOREIGN KEY (reported_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.driver_info
    ADD CONSTRAINT driver_info_address_id_fkey FOREIGN KEY (address_id)
    REFERENCES public.address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.driver_info
    ADD CONSTRAINT driver_info_agency_id_fkey FOREIGN KEY (agency_id)
    REFERENCES public.agencies (agency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.driver_reviews
    ADD CONSTRAINT driver_reviews_driver_id_fkey FOREIGN KEY (driver_id)
    REFERENCES public.driver_info (driver_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.driver_reviews
    ADD CONSTRAINT driver_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.motorbike_documentation
    ADD CONSTRAINT motorbike_documentation_bike_id_fkey FOREIGN KEY (bike_id)
    REFERENCES public.bikes (bike_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.motorbike_reviews
    ADD CONSTRAINT motorbike_reviews_bike_id_fkey FOREIGN KEY (bike_id)
    REFERENCES public.bikes (bike_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.motorbike_reviews
    ADD CONSTRAINT motorbike_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_info
    ADD CONSTRAINT payment_info_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.booking_info (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pickup_info
    ADD CONSTRAINT pickup_info_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.booking_info (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.return_info
    ADD CONSTRAINT return_info_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.booking_info (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_address_id_fkey FOREIGN KEY (address_id)
    REFERENCES public.address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;